# Generated by Django 5.1 on 2025-05-01 09:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=120, null=True)),
                ('auth_provider', models.CharField(blank=True, choices=[('email', 'email'), ('google', 'google'), ('facebook', 'facebook'), ('apple', 'apple')], max_length=15, null=True)),
                ('account_status', models.CharField(blank=True, choices=[('disabled', 'disabled'), ('enabled', 'enabled'), ('suspended', 'suspended'), ('deleted', 'deleted')], max_length=15, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_number_verified', models.BooleanField(default=False)),
                ('about', models.CharField(blank=True, default='', max_length=200)),
                ('profile_pic', models.ImageField(blank=True, default='', upload_to='profile')),
                ('country', models.CharField(blank=True, default='', max_length=120)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], default='Undisclosed', max_length=50)),
                ('address', models.TextField(blank=True, default='', max_length=200)),
                ('nickname', models.CharField(blank=True, default='', max_length=120)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
