# Generated by Django 5.1 on 2025-05-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userfollowing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollowing',
        ),
    ]
