# Generated by Django 5.1 on 2025-05-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('enabled', 'Enabled'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='enabled', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(blank=True, default='https://eu.ui-avatars.com/api/?name=Patrick+maarek&size=250'),
        ),
    ]
