# Generated by Django 5.1 on 2025-05-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_is_active_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(blank=True, default='https://eu.ui-avatars.com/api/?name=Amit+Kumar&size=450'),
        ),
    ]
