# Generated by Django 5.1 on 2025-05-05 07:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('duration', models.PositiveIntegerField()),
                ('subscription_type', models.CharField(choices=[('FEATURED_DRESSING', 'FEATURED_DRESSING'), ('SELLER', 'SELLER'), ('TRENDING_SEARCH', 'TRENDING_SEARCH'), ('BOOSTED_VISIBILITY', 'BOOSTED_VISIBILITY')], max_length=200)),
                ('is_weekly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscribe_at', models.DateTimeField(auto_now_add=True)),
                ('expire_on', models.DateTimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_details', to='subscription.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
