# Generated by Django 5.1 on 2025-05-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
