# Generated by Django 5.1 on 2025-05-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='translation_key',
            field=models.CharField(default='', max_length=200),
        ),
    ]
