# Generated by Django 5.1 on 2025-05-12 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_favoriteitem_item_alter_favoriteitem_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_methods', models.CharField(max_length=100)),
                ('delivery_details', models.TextField()),
                ('payment_methods', models.CharField(max_length=100)),
                ('final_price', models.FloatField()),
                ('is_rated', models.BooleanField(default=False)),
                ('sale_status', models.CharField(choices=[('Shipped', 'Shipped'), ('NotShipped', 'NotShipped'), ('Completed', 'Completed')], default='NotShipped', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='shop.shopitem')),
            ],
        ),
    ]
