# Generated by Django 5.1 on 2025-05-12 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('report_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_report_by', to=settings.AUTH_USER_MODEL)),
                ('report_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_report_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
